/**
* @description       : CustomException Class is used for handling specific exceptions in the application.
*                      This class extends the base Exception class and can be used to throw and catch custom exceptions with meaningful messages.
* author             : Minuscule Technologies 
* @group             : 
* @last modified on  : 07-10-2025
* last modified by   : 
**/
/**
 * @description A custom exception class used for handling specific exceptions in the application.
 * This class extends the base Exception class and can be used to throw and catch custom exceptions with meaningful messages.
 */
public class CustomException extends Exception{
}